### PR TITLE
Chore(Documentation): English - Enhance the documentation

### PR DESCRIPTION
**Pull request by mrmm**
### Context

To have more straightforward and better documentation, I have made some changes to the file names :
- Replaced `、` by `-` in all documentation file names
- Fixup links in the `README.md` file
- Rerun translation on English files to fixup missed words and sentences
- Added Tables of content at the top of each page
- Changes the number of each chapter to use Romain numbers

### CODE REVIEW

**Comment by mrmm** [comment]
@Mikaelemmmm I have prepared this PR to enhance the documentation. 
I let you review the PR and let me know what to change if any 🙏

**Comment by Mikaelemmmm** [comment]
> @Mikaelemmmm I have prepared this PR to enhance the documentation. I let you review the PR and let me know what to change if any 🙏

Thank you very much

**Comment by Mikaelemmmm** [comment]
> @Mikaelemmmm I have prepared this PR to enhance the documentation. I let you review the PR and let me know what to change if any 🙏

Thank you very much, I will look at it later today

**Comment by mrmm** [comment]
@Mikaelemmmm Thanks for merging this PR. 
Is it okay for you if I re-write the english documentation?

**Pull request merged**
